import { sql } from 'drizzle-orm'
import { index, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core'
import { sessionEndReason } from './enums.ts'
import { workspace } from './identity.ts'

const tz = { withTimezone: true, mode: 'date' } as const

export const player = pgTable(
  'player',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'restrict' }),
    externalId: text('external_id').notNull(),
    firstSeenAt: timestamp('first_seen_at', tz).notNull().defaultNow(),
    lastSeenAt: timestamp('last_seen_at', tz).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('player_workspace_external_uk').on(t.workspaceId, t.externalId)],
)

/**
 * The denominator for self-serve rate. `id` is generated by the SDK in Open(), so
 * there is deliberately NO defaultRandom() here — accepting the client's uuid as the
 * primary key is what makes POST /sdk/sessions/start idempotent with no dedupe store.
 *
 * `entry_point` is context only — where in the game the player tapped support.
 * NEVER classification.
 */
export const session = pgTable(
  'session',
  {
    id: uuid('id').primaryKey(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'restrict' }),
    playerId: uuid('player_id')
      .notNull()
      .references(() => player.id, { onDelete: 'restrict' }),
    entryPoint: text('entry_point').notNull(),
    startedAt: timestamp('started_at', tz).notNull(),
    endedAt: timestamp('ended_at', tz),
    /** 'client' when sessions/end arrived; 'timeout' when the worker closed it. */
    endedBy: sessionEndReason('ended_by'),
    createdAt: timestamp('created_at', tz).notNull().defaultNow(),
  },
  (t) => [
    index('session_workspace_started_idx').on(t.workspaceId, t.startedAt),
    // The session-timeout worker's scan: unclosed sessions ordered by age.
    index('session_open_started_idx').on(t.startedAt).where(sql`ended_at is null`),
  ],
)
